### ISSUE TITLE
Print Lack of Results

### ISSUE THREAD

**Issue by Zamanry** [micahvandeusen/gMSADumper#9]
I was trying to use your tool and wasn't getting any results. I anticipate the domain I am using isn't use gMSAs. However, there is no print statement or response telling me nothing was found. So I am unsure if the tool just failed or no gMSAs exists.

**Comment by micahvandeusen** [comment]
This should be fixed in https://github.com/micahvandeusen/gMSADumper/commit/c516a5333cfff92eddc5f2909e579d818ebc2479

**Comment by Zamanry** [comment]
Wow, love the quick work you made of all the issues! Thanks!
